### ISSUE TITLE
tests not run by travis

### ISSUE THREAD

**Issue by sigu** [Podiihq/nailinda#114]
Travis is not running tests. Maybe the lower script is taking precedence so it's only checking on linting
```yaml
before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate
script:
  - mix test
script:
- make lint
```
